version: '2.2'

x-common-variables: &common-variables
  MYSQL_DATABASE: cupcakes_store
  MYSQL_USER: cupcakes_store
  MYSQL_PASSWORD: cupcakes_store
  MYSQL_PORT: 3306
  MYSQL_HOST: "db_capcakes"

services:
  mysql_db:
    image: mysql:5.7
    container_name: db_capcakes
    restart: always
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: BDBD03C7E6D2A1BB01C7698E2BD1CC12
    volumes:
      - dbdata:/var/lib/mysql
      - ./bd/cupcakes_store.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      cupcakes-store:

volumes:
  dbdata:

networks:
  cupcakes-store:

