version: '3'
services:
  web-node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - ${PORT_SOCKET}:${PORT_SOCKET}
      - ${PORT}:${PORT}
