-- MySQL Script generated by MySQL Workbench
-- Sat Oct 28 17:59:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cupcakes_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cupcakes_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cupcakes_store` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cupcakes_store` ;

-- -----------------------------------------------------
-- Table `cupcakes_store`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `nomeUsuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `Cliente_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cupcakes_store`.`Usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(255) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `codigoPostal` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `Funcionario_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cupcakes_store`.`Usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Gerente` (
  `idGerente` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `departamento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idGerente`),
  UNIQUE INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `Gerente_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cupcakes_store`.`Usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Situacao` (
  `idSituacao` INT NOT NULL AUTO_INCREMENT,
  `situacao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idSituacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `dataPedido` DATE NOT NULL,
  `situacao_id` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `situacao_id` (`situacao_id` ASC) VISIBLE,
  CONSTRAINT `Pedido_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cupcakes_store`.`Usuario` (`idUsuario`),
  CONSTRAINT `Pedido_ibfk_2`
    FOREIGN KEY (`situacao_id`)
    REFERENCES `cupcakes_store`.`Situacao` (`idSituacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `tamanho` VARCHAR(50) NOT NULL,
  `recheio` VARCHAR(255) NOT NULL,
  `cobertura` VARCHAR(255) NOT NULL,
  `massa` VARCHAR(50) NOT NULL,
  `peso` DECIMAL(10,2) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `isStatus` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTelefone`, `Usuario_idUsuario`),
  INDEX `fk_Telefone_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `cupcakes_store`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Usuario_has_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Usuario_has_Endereco` (
  `Usuario_idUsuario` INT NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Endereco_idEndereco`),
  INDEX `fk_Usuario_has_Endereco_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Endereco_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Endereco_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `cupcakes_store`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Endereco_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `cupcakes_store`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cupcakes_store`.`Pedido_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cupcakes_store`.`Pedido_has_Produto` (
  `idItensProduto` INT NOT NULL AUTO_INCREMENT,
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `quantidade` INT(6) NOT NULL,
  `precoTotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idItensProduto`, `Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `cupcakes_store`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `cupcakes_store`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
