FROM mysql:latest
# FROM mysql:5.7.32

# ENV MYSQL_DATABASE='db_cupcakes'
ENV MYSQL_PASSWORD='pipoca123'
ENV MYSQL_PORT=3306
ENV MYSQL_HOST='db'
ENV MYSQL_ROOT_PASSWORD='pipoca123'
ENV COMPOSE_PROJECT_NAME='cupcakes_store'
ENV ENV=dev

VOLUME dbdata:/var/lib/mysql
